In [1]:
import pandas as pd

In [53]:
company_df=pd.read_csv("data/companies.txt",sep="\t", encoding = 'ISO-8859-1')
company_df

,permalink,name,homepage_url,category_list,status country_code,state_code,region,city,founded_at
/Organization/-Fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
/Organization/-Qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
/Organization/-The-One-Of-Them-Inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
/Organization/0-6-Com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
/Organization/004-Technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010
...,...,...,...,...,...,...,...,...,...
/Organization/Zznode-Science-And-Technology-Co-Ltd,ZZNode Science and Technology,http://www.zznode.com,Enterprise Software,operating,CHN,22,Beijing,Beijing,NaN
/Organization/Zzzzapp-Com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
/Organization/ÃEron,ÃERON,http://www.aeron.hu/,NaN,operating,NaN,NaN,NaN,NaN,01-01-2011
/Organization/ÃAsys-2,Ãasys,http://www.oasys.io/,Consumer Electronics|Internet of Things|Teleco...,operating,USA,CA,SF Bay Area,San Francisco,01-01-2014
/Organization/Ä°Novatiff-Reklam-Ve-Tanä±Tä±M-Hizmetleri-Tic,Ä°novatiff Reklam ve TanÄ±tÄ±m Hizmetleri Tic,http://inovatiff.com,Consumer Goods|E-Commerce|Internet,operating,NaN,NaN,NaN,NaN,NaN

In [58]:
#company_df.set_index('permalink', inplace=True)
company_df['permalink']=company_df['permalink'].str.lower()

len(company_df.permalink.unique())

66038

In [57]:
company_df.head()

,permalink,name,homepage_url,category_list,status country_code,state_code,region,city,founded_at
/Organization/-Fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
/Organization/-Qounter,:qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
/Organization/-The-One-Of-Them-Inc-,"(the) one of them,inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
/Organization/0-6-Com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
/Organization/004-Technologies,004 technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010

In [30]:
company_df.columns

Index(['name', 'homepage_url', 'category_list', 'status country_code',
       'state_code', 'region', 'city', 'founded_at'],
      dtype='object')

In [31]:
# identifying null values 
company_df.isnull()

,name,homepage_url,category_list,status country_code,state_code,region,city,founded_at
permalink,,,,,,,,
#fame,False,False,False,False,False,False,False,True
:Qounter,False,False,False,False,False,False,False,False
"(THE) ONE of THEM,Inc.",False,False,False,True,True,True,True,True
0-6.com,False,False,False,False,False,False,False,False
004 Technologies,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
ZZNode Science and Technology,False,False,False,False,False,False,False,True
Zzzzapp Wireless ltd.,False,False,False,False,False,False,False,False
ÃERON,False,True,False,True,True,True,True,False
Ãasys,False,False,False,False,False,False,False,False
Ä°novatiff Reklam ve TanÄ±tÄ±m Hizmetleri Tic,False,False,False,True,True,True,True,True

In [32]:
# identifying null values per colums
company_df.isnull().sum()

name                    5058
homepage_url            3148
category_list              0
status country_code     6958
state_code              8547
region                  8030
city                    8028
founded_at             15221
dtype: int64

In [33]:
#columns having at least one missing value = any()
company_df.isnull().any()

name                    True
homepage_url            True
category_list          False
status country_code     True
state_code              True
region                  True
city                    True
founded_at              True
dtype: bool

In [34]:
# summing up missing values (column-wise)
round(100*(company_df.isnull().sum()/len(company_df.index)),2)

name                    7.62
homepage_url            4.74
category_list           0.00
status country_code    10.48
state_code             12.88
region                 12.10
city                   12.10
founded_at             22.93
dtype: float64

In [35]:
# if ypu delete the missing rows , you lose data. 
# if you impute , you introduce bias 

# delete column founded_at
company_df.drop(['founded_at'], axis=1, inplace=True)
company_df.head()

,name,homepage_url,category_list,status country_code,state_code,region,city
permalink,,,,,,,
#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai
:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City
"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN
0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing
004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign

In [36]:
# Missing values in rows 
company_df[company_df.isnull().sum(axis=1)>3]

,name,homepage_url,category_list,status country_code,state_code,region,city
permalink,,,,,,,
"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN
Beijing 1000CHI Software Technology,http://www.1000chi.com/,Mobile,operating,NaN,NaN,NaN,NaN
Beans Around,http://beansaround.com/,Coffee|Delivery|Subscription Service,operating,NaN,NaN,NaN,NaN
10tracks,http://10tracks.com,iOS|Mobile|Music,operating,NaN,NaN,NaN,NaN
115 network disks,http://www.115.com/,EdTech|Education,operating,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
ZUUMTEL,http://www.zuumtel.com,Automotive|Design|Real Time,closed,NaN,NaN,NaN,NaN
"Zwayo ""On-Demand Valet Parking""",http://www.zwayo.co,Apps|Cars|Parking,operating,NaN,NaN,NaN,NaN
Zyfin,http://www.zyfin.com/,Finance,operating,NaN,NaN,NaN,NaN
ÃERON,http://www.aeron.hu/,NaN,operating,NaN,NaN,NaN,NaN
Ä°novatiff Reklam ve TanÄ±tÄ±m Hizmetleri Tic,http://inovatiff.com,Consumer Goods|E-Commerce|Internet,operating,NaN,NaN,NaN,NaN

In [41]:
#len(company_df[company_df['category_list'] != 'operating'])

In [42]:
company_df=company_df[company_df.isnull().sum(axis=1) <=3]

In [43]:
company_df.shape

(59336, 7)

In [44]:
company_df.head()

,name,homepage_url,category_list,status country_code,state_code,region,city
permalink,,,,,,,
#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai
:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City
0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing
004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign
01Games Technology,http://www.01games.hk/,Games,operating,HKG,NaN,Hong Kong,Hong Kong

In [47]:
# df of rounds2

rounds_df = pd.read_csv('data/rounds2.csv', encoding = 'unicode_escape')
rounds_df.head()

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/ORGANIZATION/-QOUNTER,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0

In [50]:
len(rounds_df.company_permalink.unique())

90247

In [51]:
rounds_df.shape

(114949, 6)

In [59]:
rounds_df['company_permalink']=rounds_df['company_permalink'].str.lower()

In [60]:
len(rounds_df.company_permalink.unique())

66370